name: docker
services:
  python:
    image: docker/python:INPUT_PYTHON_VERSION
    build:
      context: ./python
      args:
        PYTHON_VERSION: INPUT_PYTHON_VERSION
        GCLOUD_VERSION: INPUT_GCLOUD_VERSION
    ports: 
      - "8888:8888"
    volumes:
      - type: bind
        source: /home/ubuntu/github
        target: /home/python/github
      - type: bind
        source: /home/ubuntu/keys
        target: /home/python/keys
    environment:
      - NAMESPACE=dask
  r:
    image: docker/r:INPUT_R_VERSION
    build:
      context: ./r
      args:
        R_VERSION: INPUT_R_VERSION
        GCLOUD_VERSION: INPUT_GCLOUD_VERSION
        SPARK_VERSION: INPUT_SPARK_VERSION
        JAVA_VERSION: INPUT_JAVA_VERSION
    ports: 
      - "8787:8787"
    volumes:
      - type: bind
        source: /home/ubuntu/github
        target: /home/rstudio/github
      - type: bind
        source: /home/ubuntu/keys
        target: /home/rstudio/keys
    environment:
      - NAMESPACE=spark
  julia:
    image: docker/julia:INPUT_JULIA_VERSION
    build:
      context: ./julia
      args:
        JULIA_VERSION: INPUT_JULIA_VERSION
        GCLOUD_VERSION: INPUT_GCLOUD_VERSION
    ports:
      - "1234:1234"
    volumes:
      - type: bind
        source: /home/ubuntu/github
        target: /root/github
      - type: bind
        source: /home/ubuntu/keys
        target: /root/keys
    environment:
      - NAMESPACE=julia
  julia-worker:
    image: docker/julia-worker:INPUT_JULIA_VERSION
    build:
      context: ./julia-worker
      args:
        JULIA_VERSION: INPUT_JULIA_VERSION
