name: docker
services:
  python:
    image: docker/python:3.10.5
    build: ./python
    ports: 
      - "8888:8888"
    volumes:
      - type: bind
        source: /home/ubuntu/github
        target: /home/python/github
      - type: bind
        source: /home/ubuntu/keys
        target: /home/python/keys
  r:
    image: docker/r:4.2.0
    build: ./r
    ports: 
      - "8787:8787"
    volumes:
      - type: bind
        source: /home/ubuntu/github
        target: /home/rstudio/github
      - type: bind
        source: /home/ubuntu/keys
        target: /home/rstudio/keys
  julia:
    image: docker/julia:1.7.3
    build: ./julia
    ports:
      - "1234:1234"
    volumes:
      - type: bind
        source: /home/ubuntu/github
        target: /home/julia/github
  psql:
    image: postgres:14.3
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: psql
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=PASSWORD_FILE
  # mysql:
    # image: mysql:8.0.29
    # ports:
      # - "3306:3306"
    # volumes:
      # - type: volume
        # source: mysql
        # target: /var/lib/mysql
    # environment:
      # - MYSQL_ROOT_PASSWORD=PASSWORD_FILE
volumes:
  psql:
  # mysql:
