name: docker
services:
  postgres:
    image: postgres:INPUT_POSTGRES_VERSION
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data
      - type: volume
        source: s3
        target: /var/lib/postgresql/s3
      - type: volume
        source: gcs
        target: /var/lib/postgresql/gcs
    environment:
      - POSTGRES_PASSWORD=INPUT_POSTGRES_PASSWORD
  trino:
    image: trinodb/trino:INPUT_TRINO_VERSION
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./trino-catalog
        target: /etc/trino/catalog
      - type: volume
        source: trino
        target: /data/trino
      - type: volume
        source: s3
        target: /home/trino/s3
      - type: volume
        source: gcs
        target: /home/trino/gcs
    environment:
      - POSTGRES_PASSWORD=INPUT_POSTGRES_PASSWORD
  # mysql:
    # image: mysql:8.0.29
    # ports:
      # - "3306:3306"
    # volumes:
      # - type: volume
        # source: mysql
        # target: /var/lib/mysql
    # environment:
      # - MYSQL_ROOT_PASSWORD=PASSWORD_FILE
volumes:
  postgres:
  trino:
  s3:
    driver: rclone
    driver_opts:
      remote: "s3:"
      vfs_cache_mode: writes
  gcs:
    driver: rclone
    driver_opts:
      remote: "gcs:"
      vfs_cache_mode: writes
  # mysql:
