name: docker
services:
  python:
    image: us-central1-docker.pkg.dev/project-lee-1/docker/python:INPUT_PYTHON_VERSION
    build:
      context: ./python
      args:
        PYTHON_VERSION: INPUT_PYTHON_VERSION
        GCLOUD_VERSION: INPUT_GCLOUD_VERSION
    ports:
      - "8888:8888"
    volumes:
      - type: volume
        source: onedrive
        target: /root/github
      - type: volume
        source: s3
        target: /root/s3
      - type: volume
        source: gcs
        target: /root/gcs
      - type: bind
        source: /home/ubuntu/keys
        target: /root/keys
    environment:
      - NAMESPACE=dask
  r:
    image: us-central1-docker.pkg.dev/project-lee-1/docker/r:INPUT_R_VERSION
    build:
      context: ./r
      args:
        R_VERSION: INPUT_R_VERSION
        GCLOUD_VERSION: INPUT_GCLOUD_VERSION
        SPARK_VERSION: INPUT_SPARK_VERSION
        JAVA_VERSION: INPUT_JAVA_VERSION
    ports:
      - "8787:8787"
    volumes:
      - type: volume
        source: onedrive
        target: /home/rstudio/github
      - type: volume
        source: s3
        target: /home/rstudio/s3
      - type: volume
        source: gcs
        target: /home/rstudio/gcs
      - type: bind
        source: /home/ubuntu/keys
        target: /home/rstudio/keys
    environment:
      - NAMESPACE=spark
  julia:
    image: us-central1-docker.pkg.dev/project-lee-1/docker/julia:INPUT_JULIA_VERSION
    build:
      context: ./julia
      args:
        JULIA_VERSION: INPUT_JULIA_VERSION
        GCLOUD_VERSION: INPUT_GCLOUD_VERSION
    ports:
      - "1234:1234"
    volumes:
      - type: volume
        source: onedrive
        target: /root/github
      - type: volume
        source: s3
        target: /root/s3
      - type: volume
        source: gcs
        target: /root/gcs
      - type: bind
        source: /home/ubuntu/keys
        target: /root/keys
    environment:
      - NAMESPACE=julia
volumes:
  onedrive:
    driver: rclone
    driver_opts:
      remote: "onedrive:backup/github"
      vfs_cache_mode: full
  s3:
    driver: rclone
    driver_opts:
      remote: "s3:"
      vfs_cache_mode: writes
  gcs:
    driver: rclone
    driver_opts:
      remote: "gcs:"
      vfs_cache_mode: writes
