server:
  workers: 10
service:
  type: LoadBalancer
coordinator:
  resources:
    limits:
      cpu: 4
      memory: 16G
    requests:
      cpu: 4
      memory: 16G
worker:
  resources:
    limits:
      cpu: 1
      memory: 4G
    requests:
      cpu: 1
      memory: 4G
additionalCatalogs:
  postgresql: |
    connector.name=postgresql
    connection-url=jdbc:postgresql://34.172.239.100:5432/postgres
    connection-user=postgres
    connection-password=INPUT_POSTGRES_PASSWORD
