apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: julia
  name: worker
spec:
  replicas: 10
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: us-central1-docker.pkg.dev/project-lee-1/docker/julia:1.7.3
        command: ["sh", "-c", "service ssh start; tail -f /dev/null"]
        resources:
          limits:
            memory: "4G"
            cpu: "1"
          requests:
            memory: "4G"
            cpu: "1"
        ports:
        - containerPort: 22
